### PR TITLE
Block More Apps

### PR DESCRIPTION
**Pull request by aviraxp**
The smali code comes from https://github.com/SudaMod/android_frameworks_base/pull/9/commits/228cd4591461d097ec0150f2d95ba3cfc050b6ad

I am a student in School of Economics and know little about smali, if there is something I miss, please feel free to tell me.

### CODE REVIEW

**Comment by Dibel** [comment]
Thanks, I noticed this change at https://github.com/neoFelhz/ForceStopGB/commit/da9ecb1ab852254dc697b8bd02073915c5731e91, but I can't get smali code from java code. Thanks again!

**Comment by aviraxp** [comment]
In fact I decompiled services.jar from SudaMod and got the smali code, but I do not know if it really works.  Could you have a test?

**Comment by Dibel** [comment]
OK I'll test later. In fact I'm attending the class...

**Comment by aviraxp** [comment]
That will be nice (_＾-＾_) . You can test 网易严选.

**Comment by Dibel** [comment]
Tested OK. Only a small problem in the patch. I've already fixed.

**Pull request merged**
